version: "3.9"
services:
  front:
#     build:
#       context: ./front/
    image: painassasin/node_cource_project:latest
    ports:
      - 80:80
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
  api:
#     build:
#       context: ./api/
    image: ${DOCKER_LOGIN}/${DOCKER_REPOSITORY}:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./config.py:/src/project/config.py
    depends_on:
      migrations:
        condition: service_completed_successfully
  migrations:
#     build:
#       context: ./api/
    image: ${DOCKER_LOGIN}/${DOCKER_REPOSITORY}:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    volumes:
      - ./config.py:/src/project/config.py
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "sh", "migr.sh"]
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
